src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Included Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TerrUser__c.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>TerrUsers</relationshipLabel>
        <relationshipName>TerrUsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TerrUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TerrUser</label>
    <nameField>
        <displayFormat>TU-{0000}</displayFormat>
        <label>TerrUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerrUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReferenceSharingService.cls
/*
 * Created by Дмитро on 07.04.2019.
 */
public class ReferenceSharingService {
	private static Set<Territory__c> parentsTerritories = new Set<Territory__c>();

	public static List<sObject> getContactToShareAccess(List<Reference__c> newReferences) {
		List<sObject> contactToShareAccess = new List<sObject>();
		List<Account> accountsForSharingNewContacts = new List<Account>();
		List<Account> accounts = [
				SELECT Id, Territory__c
				FROM Account
				WHERE Id IN (SELECT Account__c
				FROM Reference__c
				WHERE id IN :newReferences)
		];
		for (Account acc : accounts) {
			if (acc.Territory__c != null) {
				accountsForSharingNewContacts.add(acc);
			}
		}
		Territory__c territory = [
				SELECT Id, Name, ParTerritory__c
				FROM Territory__c
				WHERE Id IN (SELECT Territory__c
				FROM Account
				WHERE Id IN :accountsForSharingNewContacts)
				LIMIT 1
		];
		Set<Territory__c> allParentTerritories = getParentHierarchyTerritories(territory);
		List<User> users = [
				SELECT Id, Name
				FROM User
				WHERE Id IN
				(SELECT User__c
				FROM TerrUser__c
				WHERE Territory__r.Id IN :allParentTerritories)
		];
		for (User user : users) {
			List<Account> accountsToShare = [SELECT Id FROM Account WHERE Territory__c = :territory.Id];
			List<Contact__Share> contactsUserShares =
					ContactSharingService.shareAccessToContact(accountsToShare, user.Id);
			contactToShareAccess.addAll(contactsUserShares);
		}
		return contactToShareAccess;
	}

	private static Set < Territory__c > getParentHierarchyTerritories(Territory__c territory) {
		parentsTerritories = new Set < Territory__c > ();
		findParentTerritories(territory);
		return parentsTerritories;
	}

	private static Set < Territory__c > findParentTerritories(Territory__c childTerritory) {
		parentsTerritories.add(childTerritory);
		List < Territory__c> territories = [SELECT Id, ParTerritory__c, Name FROM Territory__c WHERE Id =:childTerritory.ParTerritory__c];
		for (Territory__c territory : territories) {
			parentsTerritories.add(territory);
			findParentTerritories(territory);
		}
		return parentsTerritories;
	}
}