src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>ParTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Included Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TerritoryTriggerService.cls
public class TerritoryTriggerService {

    public static void isUnique(List<SObject> newTerritories) {
        List<Territory__c> insertedTerritories = (List<Territory__c>) newTerritories;
        Set<Id> parentIds = getSetIdsFromList(newTerritories, 'ParTerritory__c');
        List<Territory__c> existingRecords = [
                SELECT Id
                        , Name
                FROM Territory__c
                WHERE ParTerritory__c IN :parentIds
        ];
        Set<String> existingTerrNames = getExistingTerrNames(existingRecords);

        for (Territory__c territory : insertedTerritories) {
                if (existingTerrNames.contains(territory.Name)) {
                    territory.addError('You already have ' + territory.Name);
            }
        }
    }

    private static Set<String> getExistingTerrNames(List<Territory__c> existedTerritories) {
        Set<String> existingTerrNames = new Set<String>();
        for (Territory__c currentTerritory : existedTerritories) {
            existingTerrNames.add(currentTerritory.Name);
        }
        return existingTerrNames;
    }

    private static Set<Id> getSetIdsFromList(List<SObject> inputList, String fieldName) {
        Set<Id> resIds = new Set<Id>();
        for (SObject sobj : inputList) {
            resIds.add((Id) sobj.get(fieldName));
        }
        return resIds;
    }
}