src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>ParTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Included Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TerrUser__c.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>TerrUsers</relationshipLabel>
        <relationshipName>TerrUsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TerrUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TerrUser</label>
    <nameField>
        <displayFormat>TU-{0000}</displayFormat>
        <label>TerrUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerrUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestTerritoryUserService.cls
/*
 * Created by Дмитро on 05.04.2019.
 */
@isTest
public class TestTerritoryUserService {

	@IsTest(SeeAllData=true)
	static void createTerritoryUserMapTest(){
		List<TerrUser__c> terrUserList = [SELECT Id, User__c, Territory__c FROM TerrUser__c];
		System.assert(terrUserList.size() != 0);
		Map<Id, List<Id>> terrUserMap = new Map<Id, List<Id>>();
		Set<Id> users = new Set<Id>();
		for (TerrUser__c terrUser : terrUserList) {
			users.add(terrUser.User__c);
		}
		for (Id tempUserId : users) {
			terrUserMap.put(tempUserId, getTerritory(tempUserId, terrUserList));
		}
		System.debug(terrUserMap.values());
		System.assert(terrUserMap.size() != 0);
	}

	private static List<Id> getTerritory(Id userId, List<TerrUser__c> terrUserList) {
		List<Id> territoryList = new List<Id>();
		for (TerrUser__c terrUser : terrUserList) {
			if (terrUser.User__c == userId) {
				territoryList.add(terrUser.Territory__c);
			}
		}
		return territoryList;
	}

	@IsTest(SeeAllData = true)
	private static void getAllTerritory() {
		Id parentId = [
				SELECT Id, Name
				FROM Territory__c
				WHERE Name = 'Ukraine'
				LIMIT 1
		].Id;
		List<Territory__c> concreteResult = getAllChildsForParenTerritory(new Set<Id>{parentId});
		System.debug('concreteResult = ' + concreteResult);
	}

	private static List<Territory__c> getAllChildsForParenTerritory(Set<Id> parentId) {
		List<Territory__c> result = [SELECT Id, Name FROM Territory__c WHERE ParTerritory__c IN :parentId];
		if (result.size() > 0) {
			Set<Id> childsIds = getSetFromList(result, 'Id');
			result.addAll(getAllChildsForParenTerritory(childsIds));
			System.debug('childsIds = ' + result);
		}

		return result;
	}

	private static Set<Id> getSetFromList(List<sObject> listObjs, String searchField) {
		Set<Id> result = new Set<Id>();
		for (sObject curentSO : listObjs) {
			result.add((Id) curentSO.get(searchField));
		}
		return result;
	}
}